controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_products_like:
    path: '/products/like/{id}'
    controller: 'App\Controller\ProductController::like'
    methods: ['POST']